apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260610-145118-jqearev0ff9v-service
spec:
  selector:
    app: enterprise-system-20260610-145118-jqearev0ff9v
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
